package jp.co.info.ais.report.mapper;

import java.util.List;
import jp.co.info.ais.report.model.MUser;
import jp.co.info.ais.report.model.MUserExample;
import org.apache.ibatis.annotations.Param;

public interface MUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    long countByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int deleteByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int insert(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int insertSelective(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    List<MUser> selectByExample(MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    MUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int updateByExampleSelective(@Param("record") MUser record, @Param("example") MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int updateByExample(@Param("record") MUser record, @Param("example") MUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int updateByPrimaryKeySelective(MUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_user
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int updateByPrimaryKey(MUser record);
}