package jp.co.info.ais.report.mapper;

import java.util.List;
import jp.co.info.ais.report.model.MWorkReport;
import jp.co.info.ais.report.model.MWorkReportExample;
import jp.co.info.ais.report.model.MWorkReportKey;
import org.apache.ibatis.annotations.Param;

public interface MWorkReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    long countByExample(MWorkReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int deleteByExample(MWorkReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int deleteByPrimaryKey(MWorkReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int insert(MWorkReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int insertSelective(MWorkReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    List<MWorkReport> selectByExample(MWorkReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    MWorkReport selectByPrimaryKey(MWorkReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int updateByExampleSelective(@Param("record") MWorkReport record, @Param("example") MWorkReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int updateByExample(@Param("record") MWorkReport record, @Param("example") MWorkReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int updateByPrimaryKeySelective(MWorkReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_work_report
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    int updateByPrimaryKey(MWorkReport record);
}