package jp.co.info.ais.report.model;

public class MUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.user_id
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.age
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.email
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.etc_1
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private String etc1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.job_category
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private Integer jobCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.passwd
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.sex
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.ton_num
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private Integer tonNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.vessel_name
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private String vesselName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.vessel_type
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private Integer vesselType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_user.etc_2
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private String etc2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.user_id
     *
     * @return the value of public.m_user.user_id
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.user_id
     *
     * @param userId the value for public.m_user.user_id
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.age
     *
     * @return the value of public.m_user.age
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.age
     *
     * @param age the value for public.m_user.age
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.email
     *
     * @return the value of public.m_user.email
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.email
     *
     * @param email the value for public.m_user.email
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.etc_1
     *
     * @return the value of public.m_user.etc_1
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public String getEtc1() {
        return etc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.etc_1
     *
     * @param etc1 the value for public.m_user.etc_1
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setEtc1(String etc1) {
        this.etc1 = etc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.job_category
     *
     * @return the value of public.m_user.job_category
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public Integer getJobCategory() {
        return jobCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.job_category
     *
     * @param jobCategory the value for public.m_user.job_category
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setJobCategory(Integer jobCategory) {
        this.jobCategory = jobCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.passwd
     *
     * @return the value of public.m_user.passwd
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.passwd
     *
     * @param passwd the value for public.m_user.passwd
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.sex
     *
     * @return the value of public.m_user.sex
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.sex
     *
     * @param sex the value for public.m_user.sex
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.ton_num
     *
     * @return the value of public.m_user.ton_num
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public Integer getTonNum() {
        return tonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.ton_num
     *
     * @param tonNum the value for public.m_user.ton_num
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setTonNum(Integer tonNum) {
        this.tonNum = tonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.vessel_name
     *
     * @return the value of public.m_user.vessel_name
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public String getVesselName() {
        return vesselName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.vessel_name
     *
     * @param vesselName the value for public.m_user.vessel_name
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setVesselName(String vesselName) {
        this.vesselName = vesselName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.vessel_type
     *
     * @return the value of public.m_user.vessel_type
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public Integer getVesselType() {
        return vesselType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.vessel_type
     *
     * @param vesselType the value for public.m_user.vessel_type
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setVesselType(Integer vesselType) {
        this.vesselType = vesselType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_user.etc_2
     *
     * @return the value of public.m_user.etc_2
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public String getEtc2() {
        return etc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_user.etc_2
     *
     * @param etc2 the value for public.m_user.etc_2
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setEtc2(String etc2) {
        this.etc2 = etc2;
    }
}