package jp.co.info.ais.report.model;

public class MWorkReportKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_work_report.report_id
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private Integer reportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_work_report.user_id
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_work_report.report_id
     *
     * @return the value of public.m_work_report.report_id
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_work_report.report_id
     *
     * @param reportId the value for public.m_work_report.report_id
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_work_report.user_id
     *
     * @return the value of public.m_work_report.user_id
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_work_report.user_id
     *
     * @param userId the value for public.m_work_report.user_id
     *
     * @mbg.generated Fri May 10 13:43:28 JST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}